import './js/about-me';
// import './js/accordion.js';
import './js/benefits.js';
import './js/covers.js';
import './js/faq.js';
import './js/header.js';
import './js/projects.js';
import './js/reviews.js';
import './js/swagger-api.js';
import './js/swiper.js';
import './js/work-together.js';
